/*
 * N64 overlay reload semantics for statically linked overlays.
 *
 * On the N64, syDmaLoadOverlay() DMAs an overlay's code+data from ROM and
 * clears its bss, so every scene starts with that overlay's statics at their
 * initial values. The PS2 build links all overlays into one ELF, so the
 * linker (ps2/ps2_linkfile.ld, generated by ps2/tools/gen_arena_glue.py)
 * groups each overlay's .data and .bss into its own range. At boot the
 * initial .data image of all overlays is copied once; loading an overlay
 * then restores its .data from that copy and zeroes its .bss.
 *
 * Overlays are identified by their ROM_START value, which arena_glue.S sets
 * to (index + 1) << 24.
 */
#include <ps2/platform.h>

#include <stdint.h>
#include <string.h>

typedef struct PS2OverlayRange
{
    uintptr_t data_start, data_end, bss_start, bss_end;
} PS2OverlayRange;

extern const PS2OverlayRange gPS2OverlayRanges[];
extern const uint32_t gPS2OverlayCount;
extern const char *const gPS2OverlayNames[];
extern char __ps2_ovl_data_start[], __ps2_ovl_data_end[];

static uint8_t *sDataImage;

void ps2_overlay_state_init(void)
{
    size_t size = (size_t)(__ps2_ovl_data_end - __ps2_ovl_data_start);

    sDataImage = (uint8_t *)ps2_mem_alloc(PS2_MEM_CODE_STATIC, size ? size : 16, 16);
    if (sDataImage == NULL)
    {
        ps2_panic("overlay state: cannot allocate %u bytes", (unsigned)size);
    }
    memcpy(sDataImage, __ps2_ovl_data_start, size);
    ps2_log("overlay state: %u overlays, %u KiB initial data image", (unsigned)gPS2OverlayCount,
            (unsigned)(size / 1024));
}

void ps2_overlay_state_reset(uintptr_t rom_start)
{
    uint32_t idx = (uint32_t)(rom_start >> 24);
    const PS2OverlayRange *r;

    if (sDataImage == NULL || idx == 0 || idx > gPS2OverlayCount || (rom_start & 0xFFFFFF) != 0)
    {
        return;
    }
    r = &gPS2OverlayRanges[idx];
    if (r->data_end > r->data_start)
    {
        memcpy((void *)r->data_start, sDataImage + (r->data_start - (uintptr_t)__ps2_ovl_data_start),
               r->data_end - r->data_start);
    }
    if (r->bss_end > r->bss_start)
    {
        memset((void *)r->bss_start, 0, r->bss_end - r->bss_start);
    }
}
