#!/usr/bin/env python3
"""Generate ps2/src/memory/arena_glue.S.

The N64 build links ~66 code overlays at overlapping addresses and derives
each scene's heap bounds from overlay linker symbols (ovlN_BSS_END,
ovl1_VRAM, ...). The PS2 build links every overlay statically, so these
symbols are redefined here:

  * *_BSS_START/_BSS_END/_TEXT_*/_DATA_START/_RODATA_END -> gPS2SceneArena
  * *_VRAM                                               -> gPS2SceneArenaEnd
  * *_ROM_START == *_ROM_END == (index + 1) << 24        (size 0: syDmaLoadOverlay
    copies nothing, but the value still identifies the overlay so the PS2
    overlay-state reset can find it)

gPS2SceneArenaEnd is immediately followed by gSYFramebufferSets, reproducing
the N64 memory order the game's size arithmetic assumes.

Usage: python3 ps2/tools/gen_arena_glue.py  (run from the repo root)
"""
import os
import re
import sys

ARENA_SIZE = 6 * 1024 * 1024  # generous vs. the N64's ~2.4 MiB largest heap
FB_BYTES = 3 * 230 * 320 * 2

SUFFIXES = ["ROM_START", "ROM_END", "VRAM", "TEXT_START", "TEXT_END",
            "DATA_START", "RODATA_END", "BSS_START", "BSS_END"]


def main():
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    pat = re.compile(r"\b(ovl\d+|scmanager)_(" + "|".join(SUFFIXES) + r")\b")
    names = set()
    for d in ("src", "include"):
        for dirpath, _, files in os.walk(os.path.join(root, d)):
            if "relocData" in dirpath:
                continue
            for f in files:
                if not f.endswith((".c", ".h")):
                    continue
                with open(os.path.join(dirpath, f), encoding="utf-8", errors="replace") as fh:
                    for m in pat.finditer(fh.read()):
                        names.add(m.group(1))

    def key(n):
        return (0, int(n[3:])) if n.startswith("ovl") else (1, 0)

    overlays = sorted(names, key=key)
    out = []
    out.append("/* GENERATED by ps2/tools/gen_arena_glue.py - do not edit. */")
    out.append("/* Scene arena + N64 overlay linker symbols for the PS2 build. */")
    out.append("")
    out.append("    .section .bss.ps2arena,\"aw\",@nobits")
    out.append("    .align 7")
    out.append("    .globl gPS2SceneArena")
    out.append("gPS2SceneArena:")
    out.append("    .space 0x%X" % ARENA_SIZE)
    out.append("    .globl gPS2SceneArenaEnd")
    out.append("gPS2SceneArenaEnd:")
    out.append("    .globl gSYFramebufferSets")
    out.append("gSYFramebufferSets:")
    out.append("    .space 0x%X" % FB_BYTES)
    out.append("    .globl gPS2TopOfRam")
    out.append("gPS2TopOfRam:")
    out.append("")
    for idx, ov in enumerate(overlays):
        rom_id = (idx + 1) << 24
        out.append("/* %s */" % ov)
        for s in SUFFIXES:
            sym = "%s_%s" % (ov, s)
            out.append("    .globl %s" % sym)
            if s in ("ROM_START", "ROM_END"):
                out.append("    .set %s, 0x%08X" % (sym, rom_id))
            elif s == "VRAM":
                out.append("    .set %s, gPS2SceneArenaEnd" % sym)
            else:
                out.append("    .set %s, gPS2SceneArena" % sym)
    out.append("")
    # Overlay index table for the PS2 overlay-state reset (index = rom_id >> 24).
    out.append("    .section .rodata")
    out.append("    .align 2")
    out.append("    .globl gPS2OverlayNames")
    out.append("gPS2OverlayNames:")
    out.append("    .word 0")
    for ov in overlays:
        out.append("    .word .Lname_%s" % ov)
    # Per-overlay writable-data ranges, laid out by ps2/ps2_linkfile.ld.
    out.append("    .align 2")
    out.append("    .globl gPS2OverlayRanges")
    out.append("gPS2OverlayRanges:")
    out.append("    .word 0, 0, 0, 0")
    for ov in overlays:
        out.append("    .word __ps2_%s_data_start, __ps2_%s_data_end, __ps2_%s_bss_start, __ps2_%s_bss_end"
                   % (ov, ov, ov, ov))
    out.append("    .globl gPS2OverlayCount")
    out.append("gPS2OverlayCount:")
    out.append("    .word %d" % len(overlays))
    for ov in overlays:
        out.append(".Lname_%s: .asciz \"%s\"" % (ov, ov))
    out.append("")

    dst = os.path.join(root, "ps2", "src", "memory", "arena_glue.S")
    with open(dst, "w", newline="\n") as fh:
        fh.write("\n".join(out))
    print("wrote %s (%d overlays, arena %d KiB)" % (dst, len(overlays), ARENA_SIZE // 1024))

    members = overlay_members(root)
    ld = os.path.join(root, "ps2", "ps2_linkfile.ld")
    with open(ld, "w", newline="\n") as fh:
        fh.write(make_linkfile(overlays, members))
    print("wrote %s (%d overlay objects)" % (ld, sum(len(members.get(o, [])) for o in overlays)))


def overlay_members(root):
    """Map overlay segment name -> object basenames, from the splat yaml."""
    seg = None
    members = {}
    rx_seg = re.compile(r"^  - name:\s*(\S+)")
    rx_list = re.compile(r"^\s+- \[\s*0x[0-9A-Fa-f]+\s*,\s*\.?(?:c|data|bss|rodata)\s*,\s*([\w/]+)\s*\]")
    rx_map = re.compile(r"^\s+- \{.*\bname:\s*([\w/]+)")
    with open(os.path.join(root, "smashbrothers.us.yaml"), encoding="utf-8") as fh:
        for line in fh:
            m = rx_seg.match(line)
            if m:
                seg = m.group(1)
                continue
            if seg is None:
                continue
            m = rx_list.match(line) or rx_map.match(line)
            if m:
                obj = os.path.basename(m.group(1)) + ".o"
                lst = members.setdefault(seg, [])
                if obj not in lst:
                    lst.append(obj)
    return members


LINKFILE_HEAD = """/* GENERATED by ps2/tools/gen_arena_glue.py - do not edit.
 *
 * EE link script for the SSB64 port: the ps2sdk default linkfile
 * (Copyright 2001-2004 ps2dev, Academic Free License 2.0) plus one
 * .data and one .bss range per N64 code overlay. On the N64 every
 * syDmaLoadOverlay() re-DMAs an overlay, which resets its initialized data
 * and clears its bss; ps2/src/memory/overlay_state.c reproduces that with
 * these ranges (__ps2_<ovl>_data_start/end, __ps2_<ovl>_bss_start/end).
 */

ENTRY(__start);

PHDRS {
  text PT_LOAD;
}

SECTIONS {
	.text 0x00100000: {
		_ftext = . ;
		*(.text)
		*(.text.*)
		*(.gnu.linkonce.t*)
		KEEP(*(.init))
		KEEP(*(.fini))
		QUAD(0)
	} :text

	PROVIDE(_etext = .);
	PROVIDE(etext = .);

	.ctors ALIGN(16): {
		PROVIDE(__CTOR_LIST__ = .);
		KEEP(*crtbegin*.o(.ctors))
		KEEP(*(EXCLUDE_FILE(*crtend*.o) .ctors))
		KEEP(*(SORT(.ctors.*)))
		KEEP(*(.ctors))
		PROVIDE(__CTOR_END__ = .);
	}
	.dtors ALIGN(16): {
		PROVIDE(__DTOR_LIST__ = .);
		KEEP(*crtbegin*.o(.dtors))
		KEEP(*(EXCLUDE_FILE(*crtend*.o) .dtors))
		KEEP(*(SORT(.dtors.*)))
		KEEP(*(.dtors))
		PROVIDE(__DTOR_END__ = .);
	}

	.reginfo : { *(.reginfo) }

	.data ALIGN(128): {
		_fdata = . ;
		__ps2_ovl_data_start = .;
@DATA@
		__ps2_ovl_data_end = .;
		*(.data)
		*(.data.*)
		*(.gnu.linkonce.d*)
		SORT(CONSTRUCTORS)
	}

	.rodata ALIGN(128): {
		*(.rodata)
		*(.rodata.*)
		*(.gnu.linkonce.r*)
	}

	.rdata ALIGN(128): { *(.rdata) }
	.gcc_except_table ALIGN(128): { *(.gcc_except_table) }

	_gp = ALIGN(128) + 0x7ff0;
	.lit4 ALIGN(128): { *(.lit4) }
	.lit8 ALIGN(128): { *(.lit8) }

	.sdata ALIGN(128): {
		*(.sdata)
		*(.sdata.*)
		*(.gnu.linkonce.s*)
	}

	_edata = .;
	PROVIDE(edata = .);

	.sbss ALIGN(128) : {
		_fbss = . ;
		*(.sbss)
		*(.sbss.*)
		*(.gnu.linkonce.sb*)
		*(.scommon)
	}

	.bss ALIGN(128) : {
@BSS@
		*(.bss)
		*(.bss.*)
		*(.gnu.linkonce.b*)
		*(COMMON)
	}
	_end_bss = .;

	_end = . ;
	PROVIDE(end = .);

	.spad 0x70000000: {
		*(.spad)
	}

	PROVIDE(_heap_size = -1);
	PROVIDE(_stack = -1);
	PROVIDE(_stack_size = 128 * 1024);
}
"""


def make_linkfile(overlays, members):
    data, bss = [], []
    for ov in overlays:
        objs = members.get(ov, [])
        data.append("\t\t. = ALIGN(16); __ps2_%s_data_start = .;" % ov)
        data.extend("\t\t*libssb_game.a:%s(.data .data.*)" % o for o in objs)
        data.append("\t\t__ps2_%s_data_end = .;" % ov)
        bss.append("\t\t. = ALIGN(16); __ps2_%s_bss_start = .;" % ov)
        bss.extend("\t\t*libssb_game.a:%s(.bss .bss.* COMMON)" % o for o in objs)
        bss.append("\t\t__ps2_%s_bss_end = .;" % ov)
    return LINKFILE_HEAD.replace("@DATA@", "\n".join(data)).replace("@BSS@", "\n".join(bss))


if __name__ == "__main__":
    sys.exit(main())
