#!/usr/bin/env python3
"""Generate ps2/src/memory/arena_glue.S.

The N64 build links ~66 code overlays at overlapping addresses and derives
each scene's heap bounds from overlay linker symbols (ovlN_BSS_END,
ovl1_VRAM, ...). The PS2 build links every overlay statically, so these
symbols are redefined here:

  * *_BSS_START/_BSS_END/_TEXT_*/_DATA_START/_RODATA_END -> gPS2SceneArena
  * *_VRAM                                               -> gPS2SceneArenaEnd
  * *_ROM_START == *_ROM_END == (index + 1) << 24        (size 0: syDmaLoadOverlay
    copies nothing, but the value still identifies the overlay so the PS2
    overlay-state reset can find it)

gPS2SceneArenaEnd is immediately followed by gSYFramebufferSets, reproducing
the N64 memory order the game's size arithmetic assumes.

Usage: python3 ps2/tools/gen_arena_glue.py  (run from the repo root)
"""
import os
import re
import sys

ARENA_SIZE = 6 * 1024 * 1024  # generous vs. the N64's ~2.4 MiB largest heap
FB_BYTES = 3 * 230 * 320 * 2

SUFFIXES = ["ROM_START", "ROM_END", "VRAM", "TEXT_START", "TEXT_END",
            "DATA_START", "RODATA_END", "BSS_START", "BSS_END"]


def main():
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    pat = re.compile(r"\b(ovl\d+|scmanager)_(" + "|".join(SUFFIXES) + r")\b")
    names = set()
    for d in ("src", "include"):
        for dirpath, _, files in os.walk(os.path.join(root, d)):
            if "relocData" in dirpath:
                continue
            for f in files:
                if not f.endswith((".c", ".h")):
                    continue
                with open(os.path.join(dirpath, f), encoding="utf-8", errors="replace") as fh:
                    for m in pat.finditer(fh.read()):
                        names.add(m.group(1))

    def key(n):
        return (0, int(n[3:])) if n.startswith("ovl") else (1, 0)

    overlays = sorted(names, key=key)
    out = []
    out.append("/* GENERATED by ps2/tools/gen_arena_glue.py - do not edit. */")
    out.append("/* Scene arena + N64 overlay linker symbols for the PS2 build. */")
    out.append("")
    out.append("    .section .bss.ps2arena,\"aw\",@nobits")
    out.append("    .align 7")
    out.append("    .globl gPS2SceneArena")
    out.append("gPS2SceneArena:")
    out.append("    .space 0x%X" % ARENA_SIZE)
    out.append("    .globl gPS2SceneArenaEnd")
    out.append("gPS2SceneArenaEnd:")
    out.append("    .globl gSYFramebufferSets")
    out.append("gSYFramebufferSets:")
    out.append("    .space 0x%X" % FB_BYTES)
    out.append("    .globl gPS2TopOfRam")
    out.append("gPS2TopOfRam:")
    out.append("")
    for idx, ov in enumerate(overlays):
        rom_id = (idx + 1) << 24
        out.append("/* %s */" % ov)
        for s in SUFFIXES:
            sym = "%s_%s" % (ov, s)
            out.append("    .globl %s" % sym)
            if s in ("ROM_START", "ROM_END"):
                out.append("    .set %s, 0x%08X" % (sym, rom_id))
            elif s == "VRAM":
                out.append("    .set %s, gPS2SceneArenaEnd" % sym)
            else:
                out.append("    .set %s, gPS2SceneArena" % sym)
    out.append("")
    # Overlay index table for the PS2 overlay-state reset (index = rom_id >> 24).
    out.append("    .section .rodata")
    out.append("    .align 2")
    out.append("    .globl gPS2OverlayNames")
    out.append("gPS2OverlayNames:")
    out.append("    .word 0")
    for ov in overlays:
        out.append("    .word .Lname_%s" % ov)
    out.append("    .globl gPS2OverlayCount")
    out.append("gPS2OverlayCount:")
    out.append("    .word %d" % len(overlays))
    for ov in overlays:
        out.append(".Lname_%s: .asciz \"%s\"" % (ov, ov))
    out.append("")

    dst = os.path.join(root, "ps2", "src", "memory", "arena_glue.S")
    with open(dst, "w", newline="\n") as fh:
        fh.write("\n".join(out))
    print("wrote %s (%d overlays, arena %d KiB)" % (dst, len(overlays), ARENA_SIZE // 1024))


if __name__ == "__main__":
    sys.exit(main())
